# Generated by Django 4.2.9 on 2024-01-30 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
