# Generated by Django 4.2.9 on 2024-01-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_verificationcode_registration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
