# Generated by Django 4.2.9 on 2024-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_content_alter_message_content'),
        ('users', '0010_alter_verificationcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_box',
            field=models.ManyToManyField(blank=True, related_name='message_inbox', to='posts.message', verbose_name='전달받은 메세지 목록'),
        ),
    ]
